---
name: Publish betterops crate

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Publish crate
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: |
          cargo publish --token $CRATES_TOKEN